### ISSUE TITLE
Custom comparison broken since 0.3.4?

### ISSUE THREAD

**Issue by topalovic** [liufengyun/hashdiff#32]
Hello there.

I've been using your gem to compare large hashes of arrays with a custom comparison method and it's been working great so far.

After upgrading to 0.3.4, custom comparison seems to be broken. If you test your own example from the README:

```ruby
a = {a:'car', b:['boat', 'plane'] }
b = {a:'bus', b:['truck', ' plan'] }

diff = HashDiff.diff(a, b) do |path, obj1, obj2|
  case path
  when 'b[*]'
    obj1.length == obj2.length
  end
end

diff.should == [["~", "a", "car", "bus"], ["~", "b[1]", "plane", " plan"], ["-", "b[0]", "boat"], ["+", "b[0]", "truck"]]
```

you'll get a different output:

```ruby
diff
#=> [["~", "a", "car", "bus"], ["-", "b[1]", "plane"], ["-", "b[0]", "boat"], ["+", "b[0]", "truck"], ["+", "b[1]", " plan"]]
```

Has the API for custom comparison changed in the meantime and the docs are outdated, or is this a bug?

Thanks for the great work so far :-)

**Comment by liufengyun** [comment]
Thanks for reporting @topalovic . Sorry I'm a little busy recently, are you interested in debugging the problem and make a PR?

**Comment by grumpit** [comment]
Yes, something definitely seems broken in the `custom_compare` method. I get the following error when trying to use `strip: true`, even using your example from the README:
```ruby
2.3.5 :020 > a = {x:5, s:'foo '}
 => {:x=>5, :s=>"foo "} 
2.3.5 :021 > b = {x:6, s:'foo'}
 => {:x=>6, :s=>"foo"} 
2.3.5 :023 > diff = HashDiff.diff(a, b, :comparison => { :numeric_tolerance => 0.1, :strip => true })
NoMethodError: undefined method `call' for {:numeric_tolerance=>0.1, :strip=>true}:Hash
Did you mean?  caller
	from /usr/local/rvm/gems/ruby-2.3.5/gems/hashdiff-0.3.7/lib/hashdiff/util.rb:121:in `custom_compare'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/hashdiff-0.3.7/lib/hashdiff/diff.rb:92:in `diff'
	from (irb):23
	from /usr/local/rvm/gems/ruby-2.3.5/gems/railties-4.2.10/lib/rails/commands/console.rb:110:in `start'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/railties-4.2.10/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```
This also happens with a single key/value pair in the `comparison` hash, i.e.
```ruby
diff = HashDiff.diff(a, b, :comparison => { :strip => true })
# results in the same error, just with this hash
NoMethodError: undefined method `call' for {:strip=>true}:Hash
```

**Comment by pchaganti** [comment]
👍
